 use_frameworks!

 platform :ios, '10.0'

target 'QCKJLCWorking_Example' do
    
  pod 'QCKJLCWorking', :path => '../'


  
  target 'QCKJLCWorking_Tests' do
#    inherit! :search_paths
    
    pod 'WebViewJavascriptBridge'
    pod 'AVOSCloud'
    pod 'FBSnapshotTestCase'

    
  end
end
