use_frameworks!

platform :ios, '8.0'

target 'QCKJLCWorking_Example' do
  pod 'QCKJLCWorking', :path => '../'

  target 'QCKJLCWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
